version: '3.1'

services:

  consul:
    image: consul:latest
    command: consul agent -dev -log-level=warn -ui -client=0.0.0.0
    hostname: consul
    # ports:
    #   - "8500:8500"
    networks:
      - shippy-net

  ###################################
  # Micro web to view and query service from web dashboard
  microweb:
    image: microhq/micro
    command: web --address=0.0.0.0:8080
    ports:
      - "8081:8080"
    depends_on:
      - "consul"
    environment:
      - MICRO_REGISTRY=consul
      - MICRO_REGISTRY_ADDRESS=consul
      - MICRO_API_NAMESPACE=gomicro.api
    networks:
      - shippy-net

  ###################################
  consignment-cli:
    build: ./consignment-cli
    depends_on:
      - "consul"
    environment:
      - MICRO_REGISTRY=consul
      - MICRO_REGISTRY_ADDRESS=consul
    networks:
      - shippy-net

  user-cli:
    build: ./user-cli
    depends_on:
      - "consul"
    environment:
      MICRO_REGISTRY: "consul"
      MICRO_REGISTRY_ADDRESS: "consul"
    networks:
      - shippy-net

  consignment-service:
    build: ./consignment-service
    depends_on:
      - "consul"
    # ports:
    #   - 50051:50051
    environment:
      MICRO_ADDRESS: ":50051"
      MICRO_REGISTRY: "consul"
      MICRO_REGISTRY_ADDRESS: "consul"
      DB_HOST: "datastore:27017"
    networks:
      - shippy-net

  vessel-service:
    build: ./vessel-service
    depends_on:
      - "consul"
    # ports:
    #   - 50052:50051
    environment:
      MICRO_ADDRESS: ":50051"
      MICRO_REGISTRY: "consul"
      MICRO_REGISTRY_ADDRESS: "consul"
      DB_HOST: "datastore:27017"
    networks:
      - shippy-net

  user-service:
    build: ./user-service
    depends_on:
        - "consul"
    # ports:
    #   - 50053:50051
    environment:
      MICRO_ADDRESS: ":50051"
      MICRO_REGISTRY: "consul"
      MICRO_REGISTRY_ADDRESS: "consul"
      DB_NAME: "postgres"
      DB_HOST: "database"
      DB_PORT: "5432"
      DB_USER: "postgres"
      DB_PASSWORD: "postgres"
    networks:
      - shippy-net

  datastore:
    image: mongo
    # ports:
    #   - 27017:27017
    networks:
      - shippy-net
  database:
    image: postgres
    ports:
      - 5432:5432
    networks:
      - shippy-net
networks: # 创建网络
    shippy-net:
        driver: bridge